source 'https://rubygems.org'
ruby '2.1.5'

gem 'rails', '4.1.7'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'bcrypt', '~> 3.1.7'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring',           group: :development
gem 'quiet_assets', group: :development
gem 'activerecord-session_store'
gem 'haml-rails'
gem 'simple_form'
gem 'country_select'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'font-awesome-rails'
gem 'unicorn'
gem 'capistrano-rails', group: :development
gem 'sablon'
gem 'rspec-rails'
gem 'factory_girl_rails'
gem 'shoulda'
gem 'ffaker'
gem 'capybara'
gem 'bower-rails'
gem 'angular-rails-templates'
gem 'angularjs-rails'
gem 'angular-ui-bootstrap-rails'